### ISSUE TITLE
FEATURE: Submission to f-droid?

### ISSUE THREAD

**Issue by johnstultz-work** [farmerbb/Taskbar#1]
It would be interesting to see this in f-droid for AOSP devices.

**Comment by farmerbb** [comment]
Looks like Taskbar is already in the process of being submitted: https://f-droid.org/forums/topic/taskbar/

**Comment by smichel17** [comment]
Aaand done!

**Comment by farmerbb** [comment]
F-Droid link: https://f-droid.org/repository/browse/?fdid=com.farmerbb.taskbar
