### ISSUE TITLE
Android Q desktop mode support

### ISSUE THREAD

**Issue by draxaris1010** [farmerbb/Taskbar#108]
Google made a desktop mode for Android Q and it's terrible, which is expected because it's experimental, but there are ways to use a custom interface like taskbar so make it support desktop mode.
Some tips
https://github.com/farmerbb/libtaskbar-Lawnchair-Example

**Comment by farmerbb** [comment]
Work is ongoing for Taskbar to natively support Android Q's desktop mode, see: https://www.reddit.com/r/essential/comments/fy568o/use_essential_phone_as_giant_tablet/fmynn40/

**Comment by farmerbb** [comment]
Taskbar 6.0 will be released within the next few hours with full support for Android 10's desktop mode.
