### ISSUE TITLE
Taskbar icon is not visible when Settings is open

### ISSUE THREAD

**Issue by freebrowser1** [farmerbb/Taskbar#143]
When I use the Settings in Android 10 (devices: Oneplus 6 and Xiaomi Mi Pro 8) the taskbar icon disappears and Taskbar cannot be opened, unless I click Home or switch to another app.
EDIT: I mean the Collapse button, not the icon itself (which does not show anyway as long 'Settings' is in the foreground).

It is the only app which has this problem, it appears that Android does not allow writing over the 'Settings' app, even when the 'Allow draw over other apps' is enabled.

**Comment by farmerbb** [comment]
This is, unfortunately, a restriction that recent versions of Android, including Android 10, place on apps that use overlays (such as Taskbar).  There's nothing I can do about it, however, there is a developer option on Android 11 called "Allow screen overlays on Settings" that will disable this restriction.
