### ISSUE TITLE
tapping an icon on the bar causes a system reboot while Taskbar is home screen

### ISSUE THREAD

**Issue by furkanunluturkk** [farmerbb/Taskbar#158]
ROM: LineageOS 17.1 with Android 10
Device: Samsung Galaxy Tab S5e
when the Taskbar is set as default launcher, *some times* running/opening apps by tapping on them causes an abrupt quick system reboot.
some apps are running in fullscreen yet some others are restricted by taskbar (dock). i don't know but may be switching between them is the reason of this crash.

**Comment by utzcoz** [comment]
@furkanunluturkk , can you provide exception stack trace with command `adb logcat -s AndroidRuntime:*`?

**Comment by furkanunluturkk** [comment]
> @furkanunluturkk , can you provide exception stack trace with command `adb logcat -s AndroidRuntime:*`?

sure, i'll try for it now.

**Comment by furkanunluturkk** [comment]
oh god, i just switch the default lanucher to Taskbar and it seems working fine now. i tried everything (open the apps arbitrarly) to get the crash again but no clue outa bug. interesting...

**Comment by utzcoz** [comment]
> oh god, i just switch the default lanucher to Taskbar and it seems working fine now. i tried everything (open the apps arbitrarly) to get the crash again but no clue outa bug. interesting...

Okay, if you find the crash again, you can use above method to get exception stack trace, and paste it to this issue. @furkanunluturkk can you close the issue now? And you can reopen it if you encounter the problem again.

**Comment by furkanunluturkk** [comment]
alright. i guess i better follow the most popular principle in the field: "if it works, don't touch it" :D
