### ISSUE TITLE
tapping an icon on the bar causes a system reboot

### ISSUE THREAD

**Issue by frknltrk** [farmerbb/Taskbar#159]
i've run into same issue again as i mentioned in my last closed issue #158 
this crash happens occasionally. i don't know what causes it but the orientation of the windows by means of screen rotation can be a clue.

**Comment by frknltrk** [comment]
here's the log:

--------- beginning of crash
11-03 22:48:12.660  2849  2849 E AndroidRuntime: FATAL EXCEPTION: main
11-03 22:48:12.660  2849  2849 E AndroidRuntime: Process: org.fdroid.fdroid, PID: 2849
11-03 22:48:12.660  2849  2849 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.os.IBinder.unlinkToDeath(android.os.IBinder$DeathRecipient, int)' on a null object reference
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2077)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2039)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1987)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.IWindowSession$Stub$Proxy.startMovingTask(IWindowSession.java:2072)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.View.startMovingTask(View.java:26091)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at com.android.internal.widget.DecorCaptionView.onTouch(DecorCaptionView.java:211)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.View.dispatchTouchEvent(View.java:13949)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.app.Activity.dispatchTouchEvent(Activity.java:4011)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.View.dispatchPointerEvent(View.java:14212)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5652)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7675)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7644)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7605)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7800)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7751)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7824)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:719)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
11-03 22:48:12.660  2849  2849 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-03 22:48:12.661  2849  2849 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-03 22:48:12.661  2849  2849 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
11-03 22:48:12.661  2849  2849 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
11-03 22:48:12.661  2849  2849 E AndroidRuntime:        at com.android.server.wm.TaskPositioner.unregister(TaskPositioner.java:354)
11-03 22:48:12.661  2849  2849 E AndroidRuntime:        at com.android.server.wm.TaskPositioningController.cleanUpTaskPositioner(TaskPositioningController.java:215)
11-03 22:48:12.661  2849  2849 E AndroidRuntime:        at com.android.server.wm.TaskPositioningController.startPositioningLocked(TaskPositioningController.java:181)
11-03 22:48:12.661  2849  2849 E AndroidRuntime:        at com.android.server.wm.TaskPositioningController.startMovingTask(TaskPositioningController.java:113)
11-03 22:48:12.661  2849  2849 E AndroidRuntime:        at com.android.server.wm.Session.startMovingTask(Session.java:312)
11-03 22:48:12.661  2849  2849 E AndroidRuntime:
11-03 23:31:46.962  3185  3185 E AndroidRuntime: FATAL EXCEPTION: main
11-03 23:31:46.962  3185  3185 E AndroidRuntime: Process: org.tasks, PID: 3185
11-03 23:31:46.962  3185  3185 E AndroidRuntime: java.lang.IllegalStateException: Can't change container ID of fragment ReminderControlSet{55a26d9} (7ebac861-c482-4b25-b2aa-6565208386b9) id=0x7f0a01ea TEA_ctrl_reminders_pref}: was 2131362282 now 2131362278
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.FragmentTransaction.doAddOp(FragmentTransaction.java:269)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.BackStackRecord.doAddOp(BackStackRecord.java:180)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.FragmentTransaction.replace(FragmentTransaction.java:343)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at com.todoroo.astrid.activity.TaskEditFragment.onCreateView(TaskEditFragment.kt:193)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7847)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:57)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5238)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.ActivityThread.access$3400(ActivityThread.java:219)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2026)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-03 23:31:46.962  3185  3185 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
--------- beginning of system
11-04 13:48:51.947  1139  1171 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.display
11-04 13:48:51.947  1139  1171 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.os.IBinder.unlinkToDeath(android.os.IBinder$DeathRecipient, int)' on a null object reference
11-04 13:48:51.947  1139  1171 E AndroidRuntime:        at com.android.server.wm.TaskPositioner.unregister(TaskPositioner.java:354)
11-04 13:48:51.947  1139  1171 E AndroidRuntime:        at com.android.server.wm.TaskPositioningController.cleanUpTaskPositioner(TaskPositioningController.java:215)
11-04 13:48:51.947  1139  1171 E AndroidRuntime:        at com.android.server.wm.TaskPositioningController.startPositioningLocked(TaskPositioningController.java:181)
11-04 13:48:51.947  1139  1171 E AndroidRuntime:        at com.android.server.wm.TaskPositioningController.lambda$handleTapOutsideTask$0$TaskPositioningController(TaskPositioningController.java:129)
11-04 13:48:51.947  1139  1171 E AndroidRuntime:        at com.android.server.wm.-$$Lambda$TaskPositioningController$u0oAwi82C-bAGo2JAsAc_9ZLi70.run(Unknown Source:8)
11-04 13:48:51.947  1139  1171 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
11-04 13:48:51.947  1139  1171 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
11-04 13:48:51.947  1139  1171 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
11-04 13:48:51.947  1139  1171 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
11-04 13:48:51.947  1139  1171 E AndroidRuntime:        at com.android.server.ServiceThread.run(ServiceThread.java:44)
11-04 14:51:34.670 17468 17490 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.display
11-04 14:51:34.670 17468 17490 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.os.IBinder.unlinkToDeath(android.os.IBinder$DeathRecipient, int)' on a null object reference
11-04 14:51:34.670 17468 17490 E AndroidRuntime:        at com.android.server.wm.TaskPositioner.unregister(TaskPositioner.java:354)
11-04 14:51:34.670 17468 17490 E AndroidRuntime:        at com.android.server.wm.TaskPositioningController.cleanUpTaskPositioner(TaskPositioningController.java:215)
11-04 14:51:34.670 17468 17490 E AndroidRuntime:        at com.android.server.wm.TaskPositioningController.startPositioningLocked(TaskPositioningController.java:181)
11-04 14:51:34.670 17468 17490 E AndroidRuntime:        at com.android.server.wm.TaskPositioningController.lambda$handleTapOutsideTask$0$TaskPositioningController(TaskPositioningController.java:129)
11-04 14:51:34.670 17468 17490 E AndroidRuntime:        at com.android.server.wm.-$$Lambda$TaskPositioningController$u0oAwi82C-bAGo2JAsAc_9ZLi70.run(Unknown Source:8)
11-04 14:51:34.670 17468 17490 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
11-04 14:51:34.670 17468 17490 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
11-04 14:51:34.670 17468 17490 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
11-04 14:51:34.670 17468 17490 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
11-04 14:51:34.670 17468 17490 E AndroidRuntime:        at com.android.server.ServiceThread.run(ServiceThread.java:44)
--------- beginning of main

**Comment by utzcoz** [comment]
@frknltrk if you are using the phone with the OS based on Android 10, it's maybe an AOSP bug. I have tried to fix it with commit https://android-review.googlesource.com/c/platform/frameworks/base/+/1305913, and it has been cherried-pick to some ROMs although it was abandoned because the AOSP team fixed it in Android 11. If your phone OEM provides Android 11 OTA, maybe you can try it.

**Comment by frknltrk** [comment]
> @frknltrk if you are using the phone with the OS based on Android 10, it's maybe an AOSP bug. I have tried to fix it with commit https://android-review.googlesource.com/c/platform/frameworks/base/+/1305913, and it has been cherried-pick to some ROMs although it was abandoned because the AOSP team fixed it in Android 11. If your phone OEM provides Android 11 OTA, maybe you can try it.

i guess i'm gonna have to wait for LineageOS 18.0 with Android 11. till then i'll be a bit more careful with screen rotation or whatsoever xD
thanks for this great app and your efforts!
