### ISSUE TITLE
Can't control alpha on a small screen.

### ISSUE THREAD

**Issue by OffifialMITX** [farmerbb/Taskbar#16]
Hi, my screen resolution is 480x784 and I can't set the color's alpha, neither in portrait mode nor in landscape.

Maybe you can just implement the color picker from Simply Solid, avalible on F-Droid?

**Comment by farmerbb** [comment]
Looks like the developer of that app has released his color picker as a standalone library: https://github.com/enricocid/Color-picker-library

I'll look into this further and see what I can do.

**Comment by OffifialMITX** [comment]
Thanks

Am 3. Januar 2017 21:30:18 MEZ, schrieb Braden Farmer <notifications@github.com>:
>Looks like the developer of that app has released his color picker as a
>standalone library: https://github.com/enricocid/Color-picker-library
>
>I'll look into this further and see what I can do.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/farmerbb/Taskbar/issues/16#issuecomment-270216113

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by farmerbb** [comment]
I've implemented the color picker library you've requested.  What an improvement!

The changes will be live in version 3.0.2 (or, if you wish, you can compile the master branch to use the changes immediately)
