### ISSUE TITLE
Does not work on Chromebooks running the new Android 11

### ISSUE THREAD

**Issue by jbardi** [farmerbb/Taskbar#204]
Widget Feature Crashes on Chrome OS with Android 11. I am using an Acer Chromebook Spin 713, which is one of the hatch devices that was upgraded to Android 11 with the release of Chrome OS 90. The app works as long as you do not attempt to open the widget pane, which will immediately crash Taskbar. Most newer Chromebooks will be getting Android 11, so this will have to be fixed. Have yet to see the widgets on the desktop, so for now it is just a glorified app launcher, which is useless for Chrome OS.

UPDATE: I just noticed that Taskbar is not actually crashing, rather trying to launch the widgets overlay is actually crashing the entire Android 11 virtual machine on Chrome OS. If I have other android apps running when I click the button to show the widgets, ALL of the android apps crash because the underlying virtual machine that is now being used with Android 11 is actually crashing.

Up until Android 11 on hatch devices, all other Chromebooks are running Android through a container, while hatch devices are now running it through a virtual machine, just like how crostini linux apps are run.

So, this is a bigger issue, as no single Android app should be able to crash the entire virtual machine. That is like an Android app causing your phone to reboot. The underlying system should not be unstable to the point a single android app can bring the whole system down.

**Comment by farmerbb** [comment]
Thanks, I'll take a look at this on my Spin 713 and see if I can find up with a fix.

**Comment by elijahtaylor** [comment]
Hey, I work on the Android integration with Chrome OS at Google. jbardi is right that an app shouldn't be allowed to crash the entire system. We're tracking the bug internally and working on a fix.

However, I can give you some more details about the crash we're seeing so you can hopefully fix anyway on your end.

For the DashboardActivity, we're seeing an IllegalStateException from an illegal windowingMode of -1.  From searching your code, I found the following case where the windowing mode can fall through without being set properly, and it has a carve-out for Chrome OS, which could explain why we're only seeing it there: https://github.com/farmerbb/Taskbar/blob/db983e405f8d77ab39d91c6d8c3ff1b6fdbc374f/app/src/main/java/com/farmerbb/taskbar/util/U.java#L963

I haven't looked too deeply into why this doesn't cause an error in Android 9 on Chrome OS, maybe some other system code which validated this field has changed.

**Comment by farmerbb** [comment]
@elijahtaylor Thank you so much for providing those additional details!  I was able to reproduce the crash on my Spin 713 and found that the line you mentioned was indeed the culprit.  This has now been fixed.

Thanks for all the work that you do for Android app support on Chrome OS.
