### ISSUE TITLE
Added de (German) translation

### ISSUE THREAD

**Issue by OffifialMITX** [farmerbb/Taskbar#23]
I have translated your application into `de` (*German*). Here is the xml:
```xml

```

---

*Translation made with [Stringlate](https://github.com/LonamiWebs/Stringlate).*

**Comment by OffifialMITX** [comment]
Semms to be a problem with the upload mechanism. I'll try to upload it usong another way.

**Comment by farmerbb** [comment]
@OffifialMITX is this something you are still interested in doing?

If you want, you can just paste the xml here and I can take care of the rest.

**Comment by OffifialMITX** [comment]
I'd like to, but there's [this](https://github.com/LonamiWebs/Stringlate/issues/77) little problem causing my inability to upload it somehow so we'll have to wait until the next update, sorry for that.

**Comment by OffifialMITX** [comment]
It got finally upgraded, so [here's](https://gist.github.com/d13d7b24f3740bc2276e9c6eb5e31ab3) the translation.

**Comment by farmerbb** [comment]
Thank you very much!
