### ISSUE TITLE
[Feature request]  Set default launcher in desktop mode

### ISSUE THREAD

**Issue by realquink** [farmerbb/Taskbar#242]
Hi,  Thanks for this launcher! 

I am using it on an old phone and outputting to a TV via an HDMI-C cable. I am using it as a TV box/streaming setup. I see there is a default home app option in Taskbar that lets you set your phone's home launcher but when outputting to a TV there is no way to set the launcher there but rather it defaults to Taskbar.

This launcher has such a nice UI for TVs and I would love to be able to set as default for desktop mode: https://play.google.com/store/apps/details?id=me.efesser.flauncher&gl=US

It would be great to have a feature that allows a launcher to be chosen for desktop mode that almost lies or runs on top of Taskbar so when you hit "home" it shows your desired launcher. 

Or if anyone knows of a method via ADB to achieve this it would be greatly appreciated.

Thanks for reading!

**Comment by RokeJulianLockhart** [comment]
> I see there is a default home app option in Taskbar that lets you set your phone's home launcher but when outputting to a TV there is no way to set the launcher there but rather it defaults to Taskbar.

@realquink, I'm surprised that the fact that you're outputting to a television matters, since AOSP should merely discover the display hardware. The fact that it has an embedded computer connected should be irrelevant. Have you tried connecting to a desktop monitor to compare?

**Comment by realquink** [comment]
Hey @RokeJulianLockhart, 

Thanks for the response but I ended up using this app: 
https://play.google.com/store/apps/details?id=com.irishin.buttonsremapper&hl=en_US

to map the home button on an android remote:
https://amzn.to/3CDFj90 

I use and it works well.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/farmerbb/Taskbar/issues/242#event-15408738101

@realquink, perhaps reopen and close as unplanned/invalid?
