### ISSUE TITLE
[bug] crash on android 12

### ISSUE THREAD

**Issue by GDXN** [farmerbb/Taskbar#273]
Phone: Redmi Note 9 pro, android 12 miui 14.0.5

Error message 

>java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
>
> 	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
>	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
>	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.remove(ArrayList.java:511)
	at com.farmerbb.taskbar.ui.u1.L1(TaskbarController.java:63)
	at com.farmerbb.taskb
>
>ar.ui.u1.q1(TaskbarController.java:1)
	at com.farmerbb.taskbar.ui.u1.P(Unknown Source:0)
	at com.farmerbb.taskbar.ui.d1.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by marzz89** [comment]
I'm getting crashes on Android 13 with Pixel 4 XL as of a couple of days ago as well. Which means it's it's probably a Google update that broke it. Already uninstalled and reinstalled with no difference.

I also emailed the dev but it appears he hasn't been active for a couple of years. Once I have time in a week or two, I'll fork this project and try and fix the bug

**Comment by marzz89** [comment]
Okay so I recreated the issue. If you pin ANY app to the drawer, close the drawer and click the arrow again to open it, it crashes and never opens again.

Workaround:
> Open Taskbar settings and go into Advanced and go to bottom option and create a backup.

> Go into phone settings, Apps, find Taskbar and go to Storage and clear data and cache.

> Reopen Taskbar and reconfigure your settings and layout the way you want WITHOUT pinning any apps.

> Toggle on Taskbar so that it is showing (probably has apps in there that you don't want there).

> Start opening the apps you want to be in there from your phone, not Taskbar and you'll see those apps start to populate in Taskbar drawer.

> Once all your apps are there, go into Taskbar settings again and create another backup and name it sometimes you'll remember that it is the temporary working workaround.

> Then proceed with doing your normal routine. If it starts crashing again, just restore that new backup.

**Comment by marzz89** [comment]
Yaaaay Brandon fixed the bug that was causing crashes on Android 13! Thank you. You can close this one I think

**Comment by GDXN** [comment]
Fixed with the last build
