### ISSUE TITLE
Dashboard button to mimic home button

### ISSUE THREAD

**Issue by aario** [farmerbb/Taskbar#29]
Hi,
Please add a feature like:

[x] Dashboard button to mimic home button
Tap on dashboard button will minimize all apps and goes to home screen just like pressing home button on your phone.

This cool feature can save a lot of us from wearing our physical home button out. Thanks in advance.

**Comment by aario** [comment]
Made a pull request:
https://github.com/farmerbb/Taskbar/pull/30

**Comment by farmerbb** [comment]
As mentioned in #30, I developed an alternative implementation that will be in the next release.

**Comment by aario** [comment]
Thanks mate. I just downloaded the latest version from F-Droid and I'm enjoying the white circle! :+1:
