### ISSUE TITLE
[Bug] Crashes when opening or enabling Taskbar, version 6.2.1.

### ISSUE THREAD

**Issue by ThatAnnoyingVegan** [farmerbb/Taskbar#298]
Here's log.

FATAL EXCEPTION: Thread-2
Process: com.farmerbb.taskbar, PID: 8955
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at u0.v.y(SourceFile:1)
	at u0.v.L(SourceFile:114)
	at u0.m.run(SourceFile:12)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by farmerbb** [comment]
Thanks - an updated version of 6.2.1 has now been released on Google Play with a fix for this crash.
