### ISSUE TITLE
Virtual display support with scrcpy

### ISSUE THREAD

**Issue by soulflyman** [farmerbb/Taskbar#310]
I'm testing the new feature of scrcpy where it is possible to create a virtual display (not an overlay screen) with the parameter `scrcpy  --new-display=1920x1080/140`.
But I'm unable to run Taskbar on this virtual display. It always opens on the main screen on the device itself and not on the virtual one. Is there an option I'm missing, or is this not implemented at the moment?

//sfm

**Comment by farmerbb** [comment]
Can you double check that you have desktop mode set up within Taskbar, and then try again?  If you have desktop mode enabled then it should work just fine with virtual displays via scrcpy.

**Comment by soulflyman** [comment]
Thanks for the hint. I did it in the wrong order. Creating a virtual display with scrcpy and then running taskbar did not work. But activating the desktop mode first ant then running scrcpy did work.
