### ISSUE TITLE
How to use Window Mode / Future Planning  

### ISSUE THREAD

**Issue by hwpplayer1** [farmerbb/Taskbar#34]
How can i use Window mode , and do you plan some kind of convergence (Canonical) or continuum like Microsoft , maybe you can create a small but efficient application community which makes easier to connect mobile , cloud/server and desktop to each other and other devices 

I'll be happy to connect with you with these subjects

**Comment by farmerbb** [comment]
Freeform window mode is only available on Android 7.0+ devices.  If you have a 7.0+ device then it can be accessed by following the directions in the README.

Taskbar has a sister project called [SecondScreen](https://github.com/farmerbb/SecondScreen) that, when paired with Taskbar, provides a Convergence / Continuum-like experience on stock Android devices.

**Comment by hwpplayer1** [comment]
Thanks for the information , i'll use your software and hope i can contribute it ...
