### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by krt16s** [farmerbb/Taskbar#4]
You commit multiple version with differente versioncodes. What is the best way to check what a realease is? Maybe you could `git tag` releases?

**Comment by farmerbb** [comment]
I increment the build code every time I push a new version to the Play Store, which typically occurs with every commit.  I also don't keep code published for very long before building a new Play Store release, so you can safely assume that the most current code in the master branch is the latest release (1.1.10 #67).

I realize that this is atypical for an open-source project (and I'm sure this makes things more frustrating for F-Droid), and if this project ever gains any regular contributors then this system will change.

**Comment by krt16s** [comment]
Thanks for clarifying.You are not putting any exorbitant load on us/me, so its fine as it is. Just wanted to make sure we are not building not-to-be-released versions.
