### ISSUE TITLE
Samsung free window mode

### ISSUE THREAD

**Issue by cherryleafroad** [farmerbb/Taskbar#40]
Why Samsung free window mode is unsupported? I have a Samsung tablet and I love my free window mode, but this app would truly make it more desktop like! :) Currently it's launching only full screen for me, even though the free window option is checked. I'm thinking to myself, there must be a way to launch than this way ..

**Comment by mvfsullivan** [comment]
I'm running Taskbar on my Note 8 and its running perfectly fine. All features work as expected, even better than on my OnePlus 3T. Your Samsung tablet should run just fine, or perhaps you have missed giving TaskBar the necessary permissions.

**Comment by cherryleafroad** [comment]
Taskbar didn't request any permissions actually, I surely would've accepted. I enabled the mode and launching apps using it isn't working. Interesting, what are you running, and how did you launch apps using it?

**Comment by cherryleafroad** [comment]
Now working for me. Had an OS update too, maybe that did something
