### ISSUE TITLE
Shortcut to Open, Tasker, Placement

### ISSUE THREAD

**Issue by SHKaminski** [farmerbb/Taskbar#42]
I have found this app both useful and innovative. I have a couple of requests:

1. Shortcut to Open: It looks like you recently changed the function of the "Freeform Mode" shortcut. In the past it used to open the taskbar. Now, however, it appears to toggle the freeform mode without opening the taskbar. 
This change makes perfect sense, but it removes a workaround I used to open taskbar from Tasker or other modes (fingerprint, gesture, etc).
Could you please add a widget/shortcut/activity to open taskbar? With this, I could restore the function I had before.

2. Tasker Integration: Could you add Tasker integration? This would make alternative opening even easier. In addition to a simple open, you may want to add other actions, such as freeform mode, etc.

3. Specific Placement: I believe this request is already on this list (#25), so consider this a "second." I would like to be able to alter the placement of the collapsed taskbar beyond the options now available, each corner, horizontal or vertical. Each corner is already a common place for some other UI action, so I find myself opening taskbar when I really want the other action, or vice versa.
If I could offset taskbar a little, both x and y, I could find a place for it that would interfere less with the other stock actions.

Thank you!

**Comment by vanderLo** [comment]
I would also recommend a shortcut to trigger taskbar to slide in/show up instead of toggling enable/disable. +1

**Comment by cherryleafroad** [comment]
+1 on Tasker integration

**Comment by farmerbb** [comment]
Tasker support will be available in the next release (3.9.1)

**Comment by farmerbb** [comment]
Additional Tasker features to show/hide the Taskbar, as well as open the start menu and dashboard, have just been committed to `master` and will be available in the upcoming 4.0 release.

**Comment by SHKaminski** [comment]
Thank you!
    On Saturday, August 11, 2018, 2:02:04 PM EDT, Braden Farmer <notifications@github.com> wrote:  
 
 
Additional Tasker features to show/hide the Taskbar, as well as open the start menu and dashboard, have just been committed to master and will be available in the upcoming 4.0 release.
