### ISSUE TITLE
Please be kind and intimidate Google implementing all ideas below

### ISSUE THREAD

**Issue by kyvaith** [farmerbb/Taskbar#45]
Full feature Android for desktop is the future, and You should be part of it. Would love to get rid of proprietary RemoxOS/PhoenixOS on may main station for build from source Android x86.

**Comment by catb0t** [comment]
What does that have to do with this project?

**Comment by RaspberryPiFan** [comment]
And there is android-x86 which uses this project

**Comment by farmerbb** [comment]
Closing, Taskbar has added a lot of new features in the 2½ years since this bug was opened that bring it more in parity with Remix OS and Phoenix OS.
