### ISSUE TITLE
Recents suggestion

### ISSUE THREAD

**Issue by tengwer** [farmerbb/Taskbar#49]
Please add the abilityy to have x number of past days of recents showing. I like to have more than just the past day of recents on the bar.   It would be nice to see a greater number of my recent apps (even from more than a week ago) on the bar and not have a bunch of them disappear if I restart taskbar. Ie have abilty to display apos launched within past month etc and not just past day.  Yhank you!

**Comment by farmerbb** [comment]
Thanks for suggesting this.  I've implemented an option to show all apps in the recents tray, and will push out an update soon with this added.
