### ISSUE TITLE
Is it possible to designate particular app window "always on top"

### ISSUE THREAD

**Issue by Mahesha999** [farmerbb/Taskbar#50]
I love the app very much.

The only issue is when I want to run video in mx player inside a window and have a full screen note taking app (or a window of note taking app resized to full screen) behind the mx player. When I click on note taking app behind mx player, the mx player gets hidden behind the note taking app. I want the mx player app to stay always on top.

Is it possible to designate certain window always on top?

**Comment by farmerbb** [comment]
Unfortunately this is not possible due to Android framework limitations - Taskbar can only control how apps are launched, not how apps behave after they are launched.

**Comment by Milad-Badalzadeh** [comment]
Hey 

You can use , ((Floating Apps (Multitasking))) Apk 
Also I encourage the developer to merge this great app with ((taskbar)) project
