### ISSUE TITLE
Doesn't compile on Windows 10

### ISSUE THREAD

**Issue by MT-Dev** [farmerbb/Taskbar#53]
So I was attempting to test this out on Windows 10 using Android Studio and I couldn't get it to compile.  This is because the app/src/compat-27 file is supposed to be a symlink to the app/src/compat-26 folder.  But when cloning using gitbash it actually just comes through as a text file.

My solution was to delete the compat-27 file and re-create the symlink in gitbash.

**Comment by farmerbb** [comment]
Thanks, this was something I was meaning to fix myself for a while, but hadn't bothered :) I just fixed this in master, so it should compile fine on Windows again.
