### ISSUE TITLE
[Features Request] Search Bar

### ISSUE THREAD

**Issue by sobujbd** [farmerbb/Taskbar#69]
If possible, Please add search bar in top or bottom for find app quickly.

**Comment by farmerbb** [comment]
A search bar has already been implemented, but it's enabled by default only for devices with hardware keyboards.  If you go to General settings -> Search bar visibility, you can enable the search bar for software keyboards as well.

**Comment by sobujbd** [comment]
Yes, Got it. Thank you so much.
