### ISSUE TITLE
one app multiple window

### ISSUE THREAD

**Issue by youling257** [farmerbb/Taskbar#74]
4.0.2 can create one app multiple window, 4.0.3 can't.
I like taskbar app because it can create one app multiple window, i used this function three years.

**Comment by youling257** [comment]
![Screenshot_20191021-150058](https://user-images.githubusercontent.com/16304724/67183579-6571f080-f414-11e9-87f2-768b6b1c825c.png)
![Uploading Screenshot_20191021-150116.png…]()

**Comment by youling257** [comment]
one app create multiple window, https://drive.google.com/open?id=1EsYvcTwDhW-NHN1WhpCKdTKoyvZDaqCg

**Comment by youling257** [comment]
4.0.3, from taskbar app list, i can create one app multiple window, from taskbar recent app list, it can't.

**Comment by farmerbb** [comment]
Thanks for your report.  I have fixed this issue in the upcoming 5.0 release, which should be out in a few days.
