### ISSUE TITLE
"Show status icons and clock" crashes taskbar

### ISSUE THREAD

**Issue by EXCIDIVM** [farmerbb/Taskbar#76]
As soon as I select and save the option to "show status icons and clock" in recent apps, Taskbar crashes with a standard "application keeps crashing" system notification.
It cannot be restored no matter what until I unselect the option again.

Using Taskbar in horizontal mode. Rooted Note 9 on Pie.
Another Android 10 only feature (like desktop icons)?
Or any very exotic permission missing? I am quite sure I granted everything there is to grant, from accessibility to the ability to make system changes.

**Comment by farmerbb** [comment]
I have added a fix for this in the upcoming 5.0.1 release.

**Comment by EXCIDIVM** [comment]
I can confirm, the update completely resolved the issue for me. Showing the clock and status icons (which look amazing btw and give Taskbar even more of a PC-style feeling) no longer crashes the app.
