### ISSUE TITLE
feature request | add option to blur backround of taskbar

### ISSUE THREAD

**Issue by i0hate0you** [farmerbb/Taskbar#82]
add option to blur taskbar like taskbar on windows
so it will blur everything that is behind taskbar and start menu while opened

**Comment by farmerbb** [comment]
Thanks for the feature request.  I've looked into doing this before and it's not really feasible with Android's current APIs.  Basically in order to create a blur effect Taskbar would need access to the pixel data from the app that Taskbar overlays, which isn't really possible.
