### ISSUE TITLE
I am making czech translation

### ISSUE THREAD

**Issue by Pan00Pernicek** [farmerbb/Taskbar#84]
I will make czech translation in few days 
I am posting it here because i dont know where i should post it

**Comment by nykula** [comment]
See Polish for example https://github.com/farmerbb/Taskbar/tree/master/app/src/main/res/values-pl, you can make a values-cz directory with strings.xml like that and translate strings to your language. Also https://developer.android.com/studio/write/translations-editor can be useful.

**Comment by i0hate0you** [comment]
ok i will do it thanks

**Comment by i0hate0you** [comment]
50%  completed

**Comment by i0hate0you** [comment]
75% completed

**Comment by farmerbb** [comment]
Would you still like to contribute your translation, even if it was only partially done?

**Comment by Pan00Pernicek** [comment]
Sorry, i can't my computer (where i had it saved) have broken harddisk and motherboard.

**Comment by Pan00Pernicek** [comment]
Maybe in future.
