### ISSUE TITLE
Freeform Window Mode Not Launching Activities in Freeform Mode

### ISSUE THREAD

**Issue by commonsguy** [farmerbb/Taskbar#9]
With Taskbar set to be the home screen, the freeform mode works fine, tested with the built-in Calculator app and one of my book samples. With Taskbar in normal mode, activities do not launch in freeform mode, tested using those same activities, both before and after reboots, from the system home screen. This is on a Nexus 9 running NRD91D (7.0 with October security fixes), from a copy of Taskbar compiled from the `master` branch.

Any info you want me to collect?

**Comment by farmerbb** [comment]
When not set as the default launcher, the most reliable way to launch freeform windows is from your device's recent apps screen.  Launching apps from the home screen (when Taskbar is not set as default) is hit-or-miss, for reasons unknown to me.

**Comment by commonsguy** [comment]
OK, I can reproduce that behavior. It feels like the logic to decide what can start a freeform activity is checking to see what's in the foreground, and for some reason is not reliably determining that the home screen is in the foreground.

Thanks!

**Comment by commonsguy** [comment]
FWIW, I tossed together [another sample app](https://github.com/commonsguy/cw-omnibus/tree/master/Introspection/Freecar) applying your technique, using a notification shade tile instead of your overlay. Based on my experiments, it feels like the home screen works as a starting point if the activity had previously been launched freeform via the overview screen and that task is still outstanding. If no such previously-freeform task exists, the home screen launches the activity full-screen.

**Comment by farmerbb** [comment]
I just tested out Freecar and it looks like it's able to consistently launch apps into freeform from the home screen.  I'm thinking there's something on my end that's preventing Taskbar's start menu from reliably launching freeform windows from the home screen (I start an invisible activity whenever the start menu itself displays, I'm thinking that could be interfering).

I've already made changes to my code to allow for launching freeform windows form Taskbar's recent apps tray.

**Comment by farmerbb** [comment]
OK, changes to the Taskbar code are now live and the app can now reliably launch freeform windows from the homescreen.  Note that if an app already has a fullscreen task entry in recents, that entry needs to be cleared before Taskbar can re-launch the app in freeform mode.

I appreciate your interest in this, Mark!
